const songs = [
  {
    id: "algoNovo",
    title: "Algo Novo Vindo",
    artist: "Get Worship",
    duration: "06:30",
    audio: "assets/audio/algoNovo.wav",
    cover: "assets/images/covers/algoNovo.jpeg",
  },
  {
    id: "SorriaMusic",
    title: "Sorria / Meu Alvo",
    artist: "Comunidade das Nações",
    duration: "05:12",
    audio: "assets/audio/sorria.wav",
    cover: "assets/images/covers/sorria.jpg",
  },
  {
    id: "nossoGeneral",
    title: "Nosso General",
    artist: "Mateus Brito",
    duration: "04:12",
    audio: "assets/audio/NossoGeneral.mp3",
    cover: "assets/images/covers/nossoGeneral.jpg",
  },
  {
    id: "eleFaz",
    title: "Ele Faz",
    artist: "Robert Lucas",
    duration: "03:41",
    audio: "assets/audio/EleFaz.mp3",
    cover: "assets/images/covers/eleFaz.jpg",
  },
  {
    id: "aquiVou",
    title: "Aqui Vou Eu",
    artist: "NOVA",
    duration: "04:20",
    audio: "assets/audio/AquiVou.mp3",
    cover: "assets/images/covers/aquiVou.jpg",
  },
  {
    id: "naoPare",
    title: "Não Pare de Crer",
    artist: "Preto no Branco",
    duration: "03:40",
    audio: "assets/audio/naoPare.mp3",
    cover: "assets/images/covers/naoPare.jpeg",
  },
  {
    id: "estacoes",
    title: "Estações",
    artist: "Dunamis Music",
    duration: "07:43",
    audio: "assets/audio/Estacoes.mp3",
    cover: "assets/images/covers/estacoes.jpg",
  },
  {
    id: "fenomenal",
    title: "Phenomena DA DA",
    artist: "RCS Young",
    duration: "02:45",
    audio: "assets/audio/Fenomenal.mp3",
    cover: "assets/images/covers/fenomenal.jpeg",
  },
];

const videoLessons = [
  {
    songId: "Sorria",
    songTitle: "Sorria / Meu Alvo",
    lessons: [
      {
        id: "sorria-completo",
        title: "Coreografia Completa",
        duration: "3:35",
        thumbnail: "assets/images/videos/Sorria-CP.png",
        videoUrl: "https://www.youtube.com/embed/SRYyGJqIBOE",
        externalUrl: "https://www.youtube.com/watch?v=SRYyGJqIBOE",
      },
      {
        id: "sorria-parte-1",
        title: "Passo a Passo — Refrão",
        duration: "1:24",
        thumbnail: "assets/images/videos/Sorria-PP.png",
        videoUrl: "https://www.youtube.com/embed/V378E1yK7UU",
        externalUrl: "https://www.youtube.com/watch?v=V378E1yK7UU",
      },
    ],
  },
  {
    songId: "AlgoNovo",
    songTitle: "Algo Novo Vindo",
    lessons: [
      {
        id: "algo-novo-completo",
        title: "Coreografia Completa",
        duration: "4:33",
        thumbnail: "assets/images/videos/algo-completo.png",
        videoUrl: "https://www.youtube.com/embed/rPByn0peHXM",
        externalUrl: "https://vimeo.com/1204574370",
      },
      {
        id: "algo-novo-refrao",
        title: "Passo a Passo",
        duration: "2:19",
        thumbnail: "assets/images/videos/algo-refrao.png",
        videoUrl: "https://www.youtube.com/embed/EZZr-TuPAi8",
        externalUrl: "https://www.youtube.com/watch?v=EZZr-TuPAi8",
      },
      {
        id: "algo-novo-ponte",
        title: "Passo a Passo - Final",
        duration: "1:19",
        thumbnail: "assets/images/videos/algo-ponte.png",
        videoUrl: "https://www.youtube.com/embed/PRNW9I3wBBQ",
        externalUrl: "https://www.youtube.com/watch?v=PRNW9I3wBBQ",
      },
    ],
  },
  {
    songId: "Naopare",
    songTitle: "Não Pare de Crer",
    lessons: [
      {
        id: "nao-pare-completo",
        title: "Coreografia Completa",
        duration: "1:47",
        thumbnail: "assets/images/videos/naoPare-CC.png",
        videoUrl:
          "https://player.vimeo.com/video/1204575723?badge=0&autopause=0&player_id=0&app_id=58479",
        externalUrl: "https://vimeo.com/1204575723",
      },
      {
        id: "nao-pare-passo",
        title: "Passo a Passo",
        duration: "2:51",
        thumbnail: "assets/images/videos/naoPare-passo.png",
        videoUrl: "https://www.youtube.com/embed/ByUWagAA6vo",
        externalUrl: "https://www.youtube.com/watch?v=ByUWagAA6vo",
      },
    ],
  },
];
